apiVersion: apps/v1
kind: Deployment
metadata:
  name: obcs-service
  namespace: preprod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: obcs-service
  template:
    metadata:
      labels:
        app: obcs-service
    spec:
      containers:
        - name: obcs-service
          image: vedant7669/folio-app:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi