kind: Service
apiVersion: v1
metadata:
  name: __DEPLOYMENT_NAME__
  namespace: __SUBNAMESPACE__
spec:
  selector:
    app: __DEPLOYMENT_NAME__
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer